export const SHARED_PAG_GO_TO_PAGE = 'go_to_page'
export const SHARED_SEARCH_SEARCH_POST = 'search_search_posts'
export const POST_GET_POSTS = 'post_get_posts'
export const USER_SET_TOKEN = 'user_get_token'
export const USER_LOGIN_SUCCESS = 'user_login_success'
export const USER_LOGIN_FAIL = 'user_login_fail'
